### ISSUE TITLE
App is not working 

### ISSUE THREAD

**Issue by Satyam399** [SrikantShubam/WebSite-Classifier#1]
When i predict the websites it is showing 500 internal server error

**Comment by SrikantShubam** [comment]
Hey apologies for the late reply can you give me the list of websites you were trying to use

**Comment by SrikantShubam** [comment]
It was because of the different python versions and the scikit-learn version please ensure that scikit-learn==0.24.1 is properly installed and you are running python 3.7 , I have included in a dockerfile
