### ISSUE TITLE
I couldn't run it 

### ISSUE THREAD

**Issue by maj0rmil4d** [SrikantShubam/WebSite-Classifier#2]
Hi there, Thanks for your great work.

Can you please create a Dockerfile for this project ?

I want to run it but till now, no success!

**Comment by SrikantShubam** [comment]
Hey Miliad ,
Sorry for the late reply, I'll try to create a docker file and update you
for the same , in the meantime I'll share you my contact details as I
hardly open this email.

Thanks & Regards,
Srikant
Mob:6202130675

**Comment by SrikantShubam** [comment]
Hello I have added in a docker file the problem was because of the different Python versions the correct version is Python 3.7
